# Generated by Django 4.2.6 on 2023-11-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descripsion',
            new_name='descripcion',
        ),
    ]
